# Generated by Django 6.0.3 on 2026-03-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='hydrology.basin')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrology.measurementtype')),
            ],
            options={
                'indexes': [models.Index(fields=['basin', 'timestamp', 'measurement_type'], name='hydrology_o_basin_i_cb6245_idx')],
                'constraints': [models.UniqueConstraint(fields=('basin', 'measurement_type', 'timestamp'), name='unique_observation')],
            },
        ),
        migrations.CreateModel(
            name='RainfallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('duration_hours', models.IntegerField()),
                ('peak_value', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('min_dry_gap_used', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hydrology.basin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('basin', 'start_timestamp', 'min_dry_gap_used'), name='unique_event_per_gap')],
            },
        ),
    ]
